services:
    catalog.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
        ports:
            - "30080:8080"
            - "30081:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    sqlserver:
        environment:
            - MSSQL_SA_PASSWORD=Qwerty821@!1234
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - sql_data:/var/lib/mysql
    webgateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - IdentityUrl=http://identity-api
        ports:
                - "38880:8080"
                - "38881:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    identitydb:
        environment:
            POSTGRES_PASSWORD: Qwerty821@!123456
        ports:
            - 5432:5432
        restart: always  
        volumes:
            - identitydata:/var/lib/postgresql/data
    
    identity.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
        ports:
            - "32080:8080"
            - "32081:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    # basketdata:
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - eshop-basketdata:/data
    
    adminer.postgres:
        image: adminer
        restart: always
        ports:
        - 8080:8080
volumes:
    sql_data:
        external: true
    basketdata:
        external: false
    identitydata:
        external: true

