services:
    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        container_name: catalog.api
        build:
            context: .
            dockerfile: eShopApp/Services/Catalog.API/Dockerfile
        depends_on:
            - sqlserver
    
    sqlserver:
        image: mcr.microsoft.com/mssql/server
    
        
    webgateway:
        image: ${DOCKER_REGISTRY-}webgateway
        container_name: ocelot
        build:
            context: .
            dockerfile: ApiGateways/webGateway/Dockerfile
        depends_on:
            - catalog.api
    
    identity.api:
        image:  ${DOCKER_REGISTRY-}identityapi
        container_name: identity.api
        build:
            context: .
            dockerfile: eShopApp/Services/Identity.API/Dockerfile
        depends_on:
            - identitydb

    identitydb:
        image: postgres

    # basketdata:
    #     image: redis:alpine
    


